"""add column seeking_descr to Venue

Revision ID: 9b23f6ffb3ec
Revises: 8fdde30e14f9
Create Date: 2021-05-28 19:47:28.379304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b23f6ffb3ec'
down_revision = '8fdde30e14f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
