"""modify website_link to website in Venue and Artist

Revision ID: c925e2f609b0
Revises: 9b23f6ffb3ec
Create Date: 2021-05-30 13:31:38.368981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c925e2f609b0'
down_revision = '9b23f6ffb3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artists', 'website_link')
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website')
    op.add_column('artists', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
